/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import koneksi.koneksi;
import login.menu;
import object.object;
import static object.object.cpendaftaran;
import pendaftaran.modelpendaftaran;


/**
 *
 * @author asus
 */
public class pendaftaran extends javax.swing.JFrame {
     DefaultTableModel tbmodelpendaftaran = new DefaultTableModel();
     controlpendaftaran cp = new controlpendaftaran();
     modelpendaftaran mp = object.mdlpendaftaran;
     
    /**
     * Creates new form pendaftaran
     */
    public pendaftaran() {
        initComponents();
        tbpendaftaran.setModel(object.cpendaftaran);
        view_pelanggan();
        view_Nokamar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_pendaftaran = new javax.swing.JTextField();
        fasilitas = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        tgl_daftar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpendaftaran = new javax.swing.JTable();
        nomor_kamar = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        id_pelanggan = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR PELANGGAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 29, -1, -1));

        jLabel2.setText("ID_PENDAFTARAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 76, -1, -1));

        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 146, -1, -1));

        jLabel4.setText("NOMOR KAMAR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 186, -1, -1));

        jLabel5.setText("FASILITAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 226, -1, -1));

        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 256, -1, -1));

        jLabel7.setText("TGL_PENDAFTARAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 296, -1, -1));

        id_pendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(id_pendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 73, 260, -1));

        fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fasilitasActionPerformed(evt);
            }
        });
        getContentPane().add(fasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 216, 260, -1));

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 256, 260, -1));

        tgl_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(tgl_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 296, 260, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jButton4.setText("KEMBALI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 73, -1, 210));

        tbpendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpendaftaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpendaftaran);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 366, 617, 150));

        nomor_kamar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomor_kamarItemStateChanged(evt);
            }
        });
        nomor_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_kamarActionPerformed(evt);
            }
        });
        getContentPane().add(nomor_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 176, 130, -1));

        jLabel8.setText("ID PELANGGAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 108, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 136, 260, -1));

        id_pelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                id_pelangganItemStateChanged(evt);
            }
        });
        id_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 105, 128, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_pendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pendaftaranActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
      hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menu mn = new menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbpendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpendaftaranMouseClicked
        // TODO add your handling code here:
        int baris =  tbpendaftaran.rowAtPoint(evt.getPoint());
        String ID_PENDAFTARAN = tbpendaftaran.getValueAt(baris, 0).toString();
        id_pendaftaran.setText(ID_PENDAFTARAN);

        String ID_PELANGGAN = tbpendaftaran.getValueAt(baris, 1).toString();
        id_pelanggan.setSelectedItem(null);

        String NAMA = tbpendaftaran.getValueAt(baris, 2).toString();
        nama.setText(NAMA);

        String NO_KAMAR = tbpendaftaran.getValueAt(baris, 3).toString();
        nomor_kamar.setSelectedItem(NO_KAMAR);

        String FASILITAS = tbpendaftaran.getValueAt(baris, 4).toString();
        fasilitas.setText(FASILITAS);

        String HARGA = tbpendaftaran.getValueAt(baris, 5).toString();
        harga.setText(HARGA);

        String TGL = tbpendaftaran.getValueAt(baris, 6).toString();
        tgl_daftar.setText(TGL);
    }//GEN-LAST:event_tbpendaftaranMouseClicked

    private void nomor_kamarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomor_kamarItemStateChanged
        // TODO add your handling code here:
        try {
            Connection con = koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select fasilitas, harga from kamar where id_kamar ="+nomor_kamar.getSelectedItem();
            ResultSet res = stt.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);
                ob[1] = res.getString(2);

                fasilitas.setText((String) ob[0]);
                harga.setText((String) ob[1]);
            }
            res.close();
            stt.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_nomor_kamarItemStateChanged

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_namaActionPerformed

    private void id_pelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_id_pelangganItemStateChanged
        // TODO add your handling code here:
        try {
            Connection con = koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select nama from pelanggan where id_pelanggan ="+id_pelanggan.getSelectedItem();
            ResultSet res = stt.executeQuery(sql);

            while(res.next()){
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                nama.setText((String) ob[0]);
            }
            res.close();
            stt.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_id_pelangganItemStateChanged

    private void nomor_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_kamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_kamarActionPerformed

    private void id_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelangganActionPerformed

    private void fasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fasilitasActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void tgl_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_daftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_daftarActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            MessageFormat header = new MessageFormat("PENDAFTARAN PELANGGAN");
            MessageFormat footer = new MessageFormat("page{1,number,integer}");
            
            tbpendaftaran.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaran().setVisible(true);
            }
        });
    }
    
    private void view_pelanggan() {
         try {
            Connection con = koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select id_pelanggan from pelanggan";
            ResultSet res = stt.executeQuery(sql);
            
            while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            id_pelanggan.addItem((String) ob[0]);
        }
        res.close(); 
        stt.close();
        } catch (Exception e) {
            
        }
    }
    
    private void view_Nokamar() {
         try {
            Connection con = koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select nomor_kamar from kamar";
            ResultSet res = stt.executeQuery(sql);
            
            while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            nomor_kamar.addItem((String) ob[0]);
        }
        res.close(); 
        stt.close();
        } catch (Exception e) {
            
        }
    }
    
    
    private void kosongkanfrom(){
        id_pendaftaran.setText(null);
        id_pelanggan.setSelectedItem(null);
        nama.setText(null);
        nomor_kamar.setSelectedItem(null);
        fasilitas.setText(null);
        harga.setText(null);
        tgl_daftar.setText(null);
    }
    
    private void tambah(){
        try{
            object.cpendaftaran.insertObj( id_pendaftaran.getText(), nama.getText(),(String) nomor_kamar.getSelectedItem(), fasilitas.getText(), harga.getText(), tgl_daftar.getText());
            object.cpendaftaran.insertDB(id_pendaftaran.getText(), (String)id_pelanggan.getSelectedItem(), (String)nomor_kamar.getSelectedItem(), tgl_daftar.getText());
            
            JOptionPane.showMessageDialog(this, "Tambah data berhasil !");
            kosongkanfrom();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Tambah data gagal ??"+e);
        }
    }
    
    private void hapus(){
        try{
            int index = tbpendaftaran.getSelectedRow();
             if (index == -1){
             return;
             }
             modelpendaftaran mp = object.cpendaftaran.getModelPendaftaran(index);
             object.cpendaftaran.delete(index);
             object.cpendaftaran.deleteDB(mp);
             
             JOptionPane.showMessageDialog(this, "Data Berhasil Di hapus !");
            kosongkanfrom();
            tbpendaftaran.clearSelection();
         cp.delete(index);
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Hapus Data GagaL ??"+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fasilitas;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JComboBox id_pelanggan;
    private javax.swing.JTextField id_pendaftaran;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox nomor_kamar;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbpendaftaran;
    private javax.swing.JTextField tgl_daftar;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
