/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import login.menu;
import object.object;
import static object.object.cpendaftaran;
import static object.object.ctransaksi;
import transaksi.modeltransaksi;
import pendaftaran.modelpendaftaran;
import transaksi.controltransaksi;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author asus
 */
public class transaksi extends javax.swing.JFrame {
    
    DefaultTableModel tbmodeltransaksi = new DefaultTableModel();
    controltransaksi ct = new controltransaksi();
    modeltransaksi modelt = object.mdltransaksi;

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        loadCombo();
        tbtransaksi.setModel(object.ctransaksi);
        tambah.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        status.setEnabled(true);
        reset.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtransaksi = new javax.swing.JTable();
        ubah = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        id_transaksi = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        id_pendaftaran = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        no_kamar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fasilitas = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tgl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbtransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbtransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 137, -1, 240));

        ubah.setText("EDIT");
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 80, 73, -1));

        jButton5.setText("CARI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setText("Cari berdasarkan nama");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        reset.setText("PRINT");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 80, -1, -1));

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 222, -1));

        kembali.setText("KELUAR");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel5.setText("TRANSAKSI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("id pendaftaran");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 121, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("id transaksi :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 83, -1, -1));

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 159, -1));

        id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 81, 159, -1));

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 80, -1, -1));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 80, 73, -1));

        jToggleButton1.setText("Status");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 66, -1));

        id_pendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(id_pendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));

        jLabel1.setText("Nama pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel2.setText("No kamar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(no_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, -1));

        jLabel3.setText("Fasilitas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(fasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, -1));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setText("Tgl Transaksi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglActionPerformed(evt);
            }
        });
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, -1));

        jLabel9.setText("bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transaksiActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        menu mn = new menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(bayar.getText().equals(harga.getText())){
            status.setText("Lunas");
        }else{
            status.setText("Belum Lunas !!");
        }
        
        tambah.setEnabled(true);
        ubah.setEnabled(true);
        hapus.setEnabled(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void tbtransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtransaksiMouseClicked
        // TODO add your handling code here:
        int baris =  tbtransaksi.rowAtPoint(evt.getPoint());
        String ID_TRANSAKSI= tbtransaksi.getValueAt(baris, 0).toString();
        id_transaksi.setText(ID_TRANSAKSI);

        String ID_PENDAFTARAN = tbtransaksi.getValueAt(baris, 2).toString();
        id_pendaftaran.setSelectedItem(null);

        String NAMA = tbtransaksi.getValueAt(baris, 1).toString();
        nama.setText(NAMA);

        String NO_KAMAR = tbtransaksi.getValueAt(baris, 3).toString();
        no_kamar.setText(NO_KAMAR);

        String FASILITAS = tbtransaksi.getValueAt(baris, 4).toString();
        fasilitas.setText(FASILITAS);

        String HARGA = tbtransaksi.getValueAt(baris, 5).toString();
        harga.setText(HARGA);

        String TGL = tbtransaksi.getValueAt(baris, 6).toString();
        tgl.setText(TGL);
        
        String BAYAR = tbtransaksi.getValueAt(baris, 7).toString();
        bayar.setText(BAYAR);
        
        String STATUS = tbtransaksi.getValueAt(baris, 8).toString();
        status.setText(STATUS);
    }//GEN-LAST:event_tbtransaksiMouseClicked

    private void id_pendaftaranItemStateChanged(java.awt.event.ItemEvent evt) {                                               
        try{
            Connection con= koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select nama,no_kamar from pendaftaran where id_pendaftaran ="+id_pendaftaran.getSelectedItem();
            ResultSet res = stt.executeQuery(sql);
        
            while (res.next()){
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);
                ob[1] = res.getString(2);
                
                nama.setText((String) ob[0]);
                no_kamar.setText((String) ob[1]);
//                ob[0]=res.getString((String) ob[0]);
                id_pendaftaran.addItem((String) ob[0]);
            }
            res.close();
            stt.close();
        } catch (Exception e){
        }
    } 
    
    private void loadCombo() {
         try {
            Connection con = koneksi.getConnection();
            Statement stt = con.createStatement();
            String sql = "select id_pendaftaran from pendaftaran";
            ResultSet res = stt.executeQuery(sql);
            
            while(res.next()){
            Object[] ob = new Object[3];
            ob[0] = res.getString(1);
            
            id_pendaftaran.addItem((String) ob[0]);
        }
        res.close(); 
        stt.close();
        } catch (Exception e) {
            
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        cari();
        reset.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void id_pendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pendaftaranActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_id_pendaftaranActionPerformed

    private void tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
      // TODO add your handling code here:
                
    }//GEN-LAST:event_cariActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
          try{
            MessageFormat header = new MessageFormat("PENDAFTARAN PELANGGAN");
            MessageFormat footer = new MessageFormat("page{1,number,integer}");
            
            tbtransaksi.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }
    
    private void kosongkanfrom(){
        id_transaksi.setText(null);
        id_pendaftaran.setSelectedItem(null);
        nama.setText(null);
        no_kamar.setText(null);
        fasilitas.setText(null);
        harga.setText(null);
        tgl.setText(null);
        status.setText(null);
        bayar.setText(null);
    }
    
    private void tambah(){
        try{
            object.ctransaksi.insertObj(id_transaksi.getText(), (String) id_pendaftaran.getSelectedItem(), nama.getText(), no_kamar.getText(), fasilitas.getText(), harga.getText(), bayar.getText(), tgl.getText(), status.getText());
            object.ctransaksi.insertDB(id_transaksi.getText(),  (String)id_pendaftaran.getSelectedItem(), no_kamar.getText(), status.getText(), tgl.getText());
            
            JOptionPane.showMessageDialog(this, "Tambah data berhasil !!");
            kosongkanfrom();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Tambah data gagal ?? "+e);
        }
    }
    
    private void hapus(){
        try{
            int index = tbtransaksi.getSelectedRow();
             if (index == -1){
             return;
             }
             modeltransaksi mp = object.ctransaksi.getModelTransaksi(index);
             object.cpendaftaran.delete(index);
             
             JOptionPane.showMessageDialog(this, "Data Berhasil Di hapus !");
            kosongkanfrom();
            tbtransaksi.clearSelection();
         ct.delete(index);
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Hapus Data GagaL ??"+e);
        }
    }
    
//    private void cari(){
//        modeltransaksi mdt = object.ctransaksi. Search (jButton5.getText());
//        
//        tbmodeltransaksi.setRowCount(0);
//        tbmodeltransaksi.setColumnCount(0);
//        tbmodeltransaksi.addColumn("ID TRANSAKSI");
//        tbmodeltransaksi.addColumn("ID PENDAFTARAN");
//        tbmodeltransaksi.addColumn("NAMA");
//        tbmodeltransaksi.addColumn("NO. KAMAR");
//        tbmodeltransaksi.addColumn("FASILITAS");
//        tbmodeltransaksi.addColumn("HARGA");
//        tbmodeltransaksi.addColumn("TGL TRANSAKSI");
//        tbmodeltransaksi.addColumn("BAYARA");
//        tbmodeltransaksi.addColumn("STATUS");
//        
//        tbmodeltransaksi.addRow(new Object[]{mdt.getId_transaksi(),
//                        mdt.getTgl_transaksi(), mdt.getBayar(), mdt.getStatus()
//        });
//        
//        tbtransaksi.setModel(tbmodeltransaksi);
//        
//        
//    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField fasilitas;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JComboBox id_pendaftaran;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_kamar;
    private javax.swing.JButton reset;
    private javax.swing.JTextField status;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbtransaksi;
    private javax.swing.JTextField tgl;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
