/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import object.object;
import login.menu;

/**
 *
 * @author asus
 */
public class admin extends javax.swing.JFrame {
    DefaultTableModel tbmodeladmin = new DefaultTableModel();
    controladmin ca = new controladmin();
    modeladmin ma = object.mdladmin;
    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        tbadmin.setModel(object.cadmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbadmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 19, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 68, -1, -1));

        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 103, -1, -1));

        jLabel4.setText("password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 144, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 65, 239, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 141, 239, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 103, 239, -1));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 179, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 179, -1, -1));

        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        getContentPane().add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 179, -1, -1));

        keluar.setText("Kembali");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 179, -1, -1));

        tbadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbadminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbadmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 220, 375, 97));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
       ubah();
    }//GEN-LAST:event_UbahActionPerformed

    private void tbadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbadminMouseClicked
        // TODO add your handling code here:
        int baris = tbadmin.rowAtPoint(evt.getPoint());
        String ID = tbadmin.getValueAt(baris, 0).toString();
        id.setText(ID);
        
        String USERNAME = tbadmin.getValueAt(baris, 1).toString();
        username.setText(USERNAME);
        
        String PASSWORD = tbadmin.getValueAt(baris, 2).toString();
        password.setText(PASSWORD);
    }//GEN-LAST:event_tbadminMouseClicked

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        menu mn = new menu();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }
    
    private void kosongkan_from(){
        id.setText(null);
        username.setText(null);
        password.setText(null);
    }
    
    private void tambah(){
        try{
            object.cadmin.insertOBJ(id.getText(), username.getText(), password.getText());
            object.cadmin.insertDB(id.getText(), username.getText(), password.getText());
            
            JOptionPane.showMessageDialog(this, "tambah data berhasil !!");
            kosongkan_from();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "tambah data gagal ??"+e);
        }
    }
    
    private void ubah(){
        try{
            int index = tbadmin.getSelectedRow();
            if(index == -1){
                return;
            }
            modeladmin ma = object.cadmin.getModeladmin(index);
            ma.setID(id.getText());
            ma.setUsername(username.getText());
            ma.setPassword(password.getText());
            
            object.cadmin.update(ma, index);
            object.cadmin.updateDB(ma);
            JOptionPane.showMessageDialog(this, "Ubah data berhasil !");
            kosongkan_from();
            tbadmin.clearSelection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ubah data gagal ??"+e);
        }
    }
    
    private void hapus(){
        try{
        int index = tbadmin.getSelectedRow();
        if(index == -1){
            return;
        }
        modeladmin ma = object.cadmin.getModeladmin(index);
        object.cadmin.delete(index);
        object.cadmin.deleteDB(ma);
        
        JOptionPane.showMessageDialog(this, "Hapus data berhasil !");
        kosongkan_from();
        tbadmin.clearSelection();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Hapus data gagal ?" +e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ubah;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField password;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbadmin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
